/**
 * Catálogo ASOT: mapeos y fichas de organismos.
 * Editar este archivo para actualizar datos sin tocar la interfaz.
 */
window.ASOT_DATA = {
    datosAInformacion: {
            telefono: ['CDRs de llamadas', 'Geolocalización', 'Historial SMS', 'Información de suscriptor', 'Contactos/amigos', 'Métodos de pago asociados'],
            ip: ['Actividad de navegación', 'Identificación de usuario', 'ISP utilizado', 'Servicios accedidos', 'Historial de logins'],
            email: ['Información de cuenta', 'Historial de transacciones', 'Almacenamiento cloud', 'Actividad de login', 'Dispositivos asociados', 'Perfil de usuario'],
            cuenta_banco: ['Historial de transacciones', 'Saldos', 'Transferencias', 'Datos de registro'],
            usuario_redsocial: ['Perfil de usuario', 'Historial de accesos IP', 'Contenido público/privado', 'Mensajes directos', 'Lista de amigos'],
            vehiculo: ['Registración del vehículo', 'Datos de viaje/trayecto', 'Métodos de pago del conductor']
        },
    informacionAServicios: {
            'CDRs de llamadas': ['movistar', 'personal', 'claro', 'tuenti'],
            'Geolocalización': ['movistar', 'personal', 'claro', 'google', 'apple', 'uber', 'cabify', 'didi'],
            'Historial SMS': ['movistar', 'personal', 'claro'],
            'Información de suscriptor': ['movistar', 'personal', 'claro', 'fibertel', 'telecentro', 'apple', 'google', 'netflix'],
            'Actividad de navegación': ['fibertel', 'telecentro', 'telered', 'iplan'],
            'Identificación de usuario': ['facebook', 'whatsapp', 'google', 'mercadolibre', 'twitter'],
            'Información de cuenta': ['google', 'facebook', 'apple', 'microsoft', 'yahoo', 'dropbox', 'spotify', 'zoom'],
            'Perfil de usuario': ['facebook', 'tiktok', 'twitter', 'badoo', 'tinder', 'happn', 'snapchat'],
            'Historial de accesos IP': ['facebook', 'whatsapp', 'google', 'microsoft', 'mercadolibre', 'yahoo', 'netflix', 'sony'],
            'Historial de transacciones': ['mercadolibre', 'paypal', 'uala', 'santander', 'galicia', 'bna', 'provincia', 'apple', 'uber'],
            'Datos de viaje/trayecto': ['uber', 'cabify', 'didi'],
            'Métodos de pago del conductor': ['uber', 'cabify', 'didi']
        },
    servicios: {
            // === TELECOMUNICACIONES ===
            claro: {id: 'claro', nombre: 'Claro (AMX Argentina)', categoria: 'telecomunicaciones', queInformacion: ['Titularidad', 'CDRs', 'Geolocalización', 'SMS'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF por correo.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Oficina de Legales', email: 'oficiosjudiciales@claro.com.ar', telefono: '011-4109-8888'}], notas: 'Para IP dinámicas informan que no es posible determinar usuario sin puerto.'},
            personal: {id: 'personal', nombre: 'Telecom Personal', categoria: 'telecomunicaciones', queInformacion: ['Titularidad', 'Llamadas entrantes/salientes', 'SMS', 'Medios de recarga', 'IPs', 'IMEI'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar PDF firmado digitalmente. No brindan info de WhatsApp, Geolocalización ni BackUps.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Req. Judiciales', email: 'requerimientosjudiciales@teco.com.ar', telefono: '0810-444-0222 (Opción 2 Fax)'}], notas: 'Aclarar período exacto. No confundir con Telecom Argentina (fija).'},
            movistar: {id: 'movistar', nombre: 'Movistar', categoria: 'telecomunicaciones', queInformacion: ['Titularidad', 'CDRs', 'Geolocalización'], requisitosLegales: ['Oficio Judicial', 'Usuario de Portal'], procedimiento: 'Se debe tramitar a través del portal web exclusivo para oficios.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal Movistar', email: 'vía portal web', telefono: ''}], notas: 'Claves de portal gestionadas por Secretaría de Política Criminal.'},
            tuenti: {id: 'tuenti', nombre: 'Tuenti', categoria: 'telecomunicaciones', queInformacion: ['Titularidad de línea'], requisitosLegales: ['Oficio PDF con firma digital'], procedimiento: 'Enviar oficio por email oficial.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Req. Judiciales', email: 'reqjudiciales@telefonica.com', telefono: ''}], notas: 'Pertenece al grupo Telefónica.'},
            telecom: {id: 'telecom', nombre: 'Telecom Argentina (Fija)', categoria: 'telecomunicaciones', queInformacion: ['Titularidad', 'Llamadas', 'Datos'], requisitosLegales: ['Oficio PDF con firma digital'], procedimiento: 'Enviar PDF firmado.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Req. Judiciales', email: 'requerimientosjudiciales@teco.com.ar', telefono: ''}], notas: 'Aclarar período. No confundir con Telecom Personal.'},

            // === ISP ===
            fibertel: {id: 'fibertel', nombre: 'Fibertel - Cablevisión (Prima S.A.)', categoria: 'isp', queInformacion: ['Titularidad de IP', 'Registros de conexión'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Yamila Leigovich', email: 'legalesoficios@cablevision.com.ar', telefono: '011-5530-6516'}], notas: 'CRÍTICO: Convertir huso horario a GMT-300 en el oficio si la IP se obtuvo de un servicio extranjero.'},
            telecentro: {id: 'telecentro', nombre: 'TeleCentro S.A.', categoria: 'isp', queInformacion: ['Titularidad de IP', 'Datos de cliente'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'IP Admin / Negocios', email: 'ipadmin@telecentro.net.ar', telefono: '011-4651-0084'}], notas: 'Con copia sugerida a negocios@telecentro.net.ar'},
            telered: {id: 'telered', nombre: 'TeleRed (Ver TV S.A.)', categoria: 'isp', queInformacion: ['Titularidad de IP'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Tecnología', email: 'tecnologia@telered.net.ar', telefono: '011-4469-7452'}], notas: 'Copiar a acuadrado, ddonantueno, mcoingrate @telered.net.ar'},
            iplan: {id: 'iplan', nombre: 'IPlan (NSS S.A.)', categoria: 'isp', queInformacion: ['Titularidad de IP'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Legales', email: 'legales@iplan.com.ar', telefono: ''}], notas: ''},

            // === PLATAFORMAS ===
            facebook: {id: 'facebook', nombre: 'Facebook / Instagram', categoria: 'plataformas', queInformacion: ['Congelamiento de cuenta (90 días)', 'Record de conexiones (IPs)'], requisitosLegales: ['Oficio firmado a mano alzada por Juez, sello medalla'], procedimiento: 'Cargar PDF en el portal Law Enforcement. Se necesita email oficial para recibir el link.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Emergencias', email: 'subpoena@facebook.com', telefono: ''}, {nombre: 'Portal', email: 'facebook.com/records', telefono: ''}], notas: 'Para contenido se requiere Exhorto (MLAT). Indicar si NO SE DEBE AVISAR al usuario.'},
            whatsapp: {id: 'whatsapp', nombre: 'WhatsApp', categoria: 'plataformas', queInformacion: ['Congelamiento de cuenta', 'Record de conexiones'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Portal web igual que Facebook.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal', email: 'whatsapp.com/records', telefono: ''}], notas: 'No poseen contenido de mensajes (cifrado extremo a extremo). Petición de IP requiere fechas exactas.'},
            google: {id: 'google', nombre: 'Google', categoria: 'plataformas', queInformacion: ['IPs de sesión', 'Datos de suscriptor', 'Fecha de creación'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email oficial.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Global Law Enforcement', email: 'lis-global@google.com', telefono: ''}], notas: 'Incluir rango de fechas, URL/correo exacto y datos completos del requirente.'},
            mercadolibre: {id: 'mercadolibre', nombre: 'MercadoLibre / MercadoPago', categoria: 'plataformas', queInformacion: ['Datos de registro', 'IPs (5 meses)', 'Historial', 'Tracking MercadoEnvíos'], requisitosLegales: ['Oficio con firma digital'], procedimiento: 'Enviar PDF al correo de notificaciones.', tiempoRespuesta: 'Rápido (Estándar) / Lento (Especial)', contactos: [{nombre: 'Notificaciones', email: 'notificaciones@mercadolibre.com', telefono: '011-4640-8000 int 8876'}], notas: 'Dato clave: Nickname, Email, Nro Publicación o Tarjeta (6 primeros, 4 últimos).'},
            apple: {id: 'apple', nombre: 'Apple', categoria: 'plataformas', queInformacion: ['Registro de dispositivos', 'iCloud', 'Compras iTunes', 'Conexiones IP'], requisitosLegales: ['Formulario de Apple PDF firmado'], procedimiento: 'Enviar formulario PDF a email. Tienen portal para congelamiento.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Law Enforcement', email: 'lawenforcement@apple.com', telefono: ''}, {nombre: 'Emergencias', email: 'exigent@apple.com', telefono: ''}], notas: 'Apple NOTIFICA al usuario salvo que la orden judicial lo prohíba expresamente.'},
            microsoft: {id: 'microsoft', nombre: 'Microsoft (Hotmail, Xbox, Skype)', categoria: 'plataformas', queInformacion: ['Suscripción', 'Registro de IPs', 'Contactos'], requisitosLegales: ['Oficio firmado por Juez', 'Planilla Excel de Microsoft'], procedimiento: 'Enviar Oficio PDF + Planilla Excel. Asunto del correo estandarizado.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'LENS Team', email: 'asklcala@microsoft.com', telefono: ''}], notas: 'Asunto debe ser: PAIS - PROVINCIA - IPP/OFICIO.'},
            twitter: {id: 'twitter', nombre: 'Twitter', categoria: 'plataformas', queInformacion: ['Conservación de datos', 'Información de cuenta'], requisitosLegales: ['Oficio firmado por Juez'], procedimiento: 'Cargar a través del portal web.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal', email: 'legalrequests.twitter.com', telefono: ''}], notas: 'Buscar el User ID numérico oculto en el código fuente del perfil para asegurar el target.'},
            tiktok: {id: 'tiktok', nombre: 'TikTok', categoria: 'plataformas', queInformacion: ['Usuario', 'Email/Tel', 'IP de creación', 'Logs de login'], requisitosLegales: ['Formulario TikTok firmado y sellado'], procedimiento: 'Completar DOCX de TikTok, pasar a PDF y enviar.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'legal@tiktok.com', telefono: ''}], notas: 'Videos privados requieren orden de búsqueda.'},
            netflix: {id: 'netflix', nombre: 'Netflix', categoria: 'plataformas', queInformacion: ['Email', 'Facturación', 'IPs de streaming', 'Dispositivos'], requisitosLegales: ['Formulario Netflix firmado por Juez con sellos'], procedimiento: 'Completar PDF de Netflix y enviar por correo.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal Process', email: 'legalprocess@netflix.com', telefono: ''}], notas: 'No guarda contenido, solo metadatos de conexión y pago.'},
            spotify: {id: 'spotify', nombre: 'Spotify', categoria: 'plataformas', queInformacion: ['IPs', 'Dispositivos', 'Ubicación no exacta', 'Datos de pago'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Support', email: 'support@spotify.com', telefono: ''}], notas: ''},
            zoom: {id: 'zoom', nombre: 'Zoom', categoria: 'plataformas', queInformacion: ['Datos dispositivo', 'IP', 'Tiempos de reunión'], requisitosLegales: ['Oficio PDF firmado digitalmente'], procedimiento: 'Enviar por correo. Es necesario el Email del titular de cuenta.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Law Enforcement', email: 'lawenforcement@zoom.us', telefono: ''}], notas: ''},
            dropbox: {id: 'dropbox', nombre: 'Dropbox', categoria: 'plataformas', queInformacion: ['Nombre', 'Email', 'IPs de acceso', 'Dispositivo'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Compliance', email: 'legalcompliance@dropbox.com', telefono: ''}], notas: 'Urgencias agregar "EmergencyRequest" al Asunto.'},
            yahoo: {id: 'yahoo', nombre: 'Yahoo / Flickr', categoria: 'plataformas', queInformacion: ['IPs de alta', 'Cuentas asociadas', 'Logs de correo/Messenger'], requisitosLegales: ['Oficio firmado'], procedimiento: 'Enviar PDF firmado digitalmente o vía portal Oath.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'ar-legalpoc@yahoo-inc.com', telefono: ''}], notas: 'Permiten congelamiento por 90 días.'},
            sony: {id: 'sony', nombre: 'Sony Playstation', categoria: 'plataformas', queInformacion: ['IPs de acceso', 'Cuentas', 'Transacciones'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'LE Requests', email: 'LE_legalrequests@playstation.sony.com', telefono: ''}, {nombre: 'Emergencias', email: 'Thomas.Nguyen@sony.com', telefono: ''}], notas: 'Tracking ideal a través de compras en la tienda.'},
            airbnb: {id: 'airbnb', nombre: 'Airbnb', categoria: 'plataformas', queInformacion: ['Datos de usuario', 'Reservas'], requisitosLegales: ['Oficio PDF firmado y sellado (Inglés)'], procedimiento: 'Cargar a través del portal de autoridades o email PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal', email: 'es.airbnb.com/lert', telefono: ''}, {nombre: 'Mail', email: 'leoinfo@airbnb.com', telefono: ''}], notas: 'Airbnb notifica al usuario salvo orden judicial contraria.'},
            badoo: {id: 'badoo', nombre: 'Badoo', categoria: 'plataformas', queInformacion: ['Datos de registro', 'Conexiones'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Llenar formulario en portal web y adjuntar PDF.', tiempoRespuesta: 'Hasta 30 días', contactos: [{nombre: 'Portal', email: 'badoo.com/es/team/contacts/', telefono: ''}], notas: 'Oficio debe contener ID de usuario o Email.'},
            tinder: {id: 'tinder', nombre: 'Match - Tinder', categoria: 'plataformas', queInformacion: ['Datos de registro', 'Conexiones'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'norma.rivera@match.com', telefono: ''}], notas: ''},
            happn: {id: 'happn', nombre: 'Happn', categoria: 'plataformas', queInformacion: ['Datos de registro'], requisitosLegales: ['Oficio en francés firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'gaelle.benoist@happn.fr', telefono: ''}], notas: 'El oficio debe estar en francés.'},
            snapchat: {id: 'snapchat', nombre: 'Snapchat', categoria: 'plataformas', queInformacion: ['Datos de registro'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'lawenforcement@snapchat.com', telefono: ''}], notas: 'Portal de urgencias disponible en lawenforcement.snapchat.com/emergency'},

            // === TRANSPORTE ===
            uber: {id: 'uber', nombre: 'Uber', categoria: 'transporte', queInformacion: ['Datos de registro', 'Recibos', 'IPs', 'GPS de viaje', 'Placas/Vehículos'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'LERT', email: 'LERT@uber.com', telefono: ''}], notas: 'Conservan registros por 90 días si se solicita. Pueden notificar al usuario/conductor.'},
            cabify: {id: 'cabify', nombre: 'Cabify', categoria: 'transporte', queInformacion: ['Datos de usuario', 'Viajes'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Cargar mediante el portal Jotform de Policía.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Info', email: 'info@cabify.com', telefono: ''}, {nombre: 'Portal', email: 'cabify.jotform.com', telefono: ''}], notas: ''},
            didi: {id: 'didi', nombre: 'DiDi', categoria: 'transporte', queInformacion: ['Datos de usuario/conductor', 'Viajes'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Security', email: 'securitysc@digitalglobal.com', telefono: ''}], notas: 'Existen celulares de contacto para delitos flagrantes (Chile/Global).'},

            // === FINANCIERO ===
            uala: {id: 'uala', nombre: 'Ualá', categoria: 'financiero', queInformacion: ['Transacciones', 'Titularidad'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'legales.ar@uala.com.ar', telefono: '011-52633563'}], notas: ''},
            paypal: {id: 'paypal', nombre: 'PayPal', categoria: 'financiero', queInformacion: ['Transacciones', 'Cuentas'], requisitosLegales: ['Oficio Judicial'], procedimiento: 'Cargar en portal SafetyHub.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Law Enforcement', email: 'lawenforcement@paypal.com', telefono: ''}], notas: 'Responderán solo a correos oficiales a través de su portal.'},
            bna: {id: 'bna', nombre: 'Banco Nación (BNA)', categoria: 'financiero', queInformacion: ['Cuentas', 'Cámaras de seguridad', 'Cajeros'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF. Hay correos específicos por sucursal (ej: 0094pop@bna.com.ar).', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios/Fraudes', email: 'operaciones-atm-analisisdefraudes@bna.com.ar', telefono: ''}, {nombre: 'Seguridad (Cámaras)', email: 'ariverobrizuela@bna.com.ar', telefono: '011-4347-8644'}], notas: 'Para cámaras actuar rápidamente antes de sobrescritura.'},
            provincia: {id: 'provincia', nombre: 'Banco Provincia (BAPRO)', categoria: 'financiero', queInformacion: ['Cuentas', 'Cámaras de seguridad'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'mdjerakian@bpba.com.ar', telefono: ''}, {nombre: 'Cámaras', email: 'cctvrescatefilmaciones@bpba.com.ar', telefono: '011-4309-3907 int 23907'}], notas: ''},
            santander: {id: 'santander', nombre: 'Santander', categoria: 'financiero', queInformacion: ['Cuentas', 'Transacciones'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios', email: 'oficiosdeinformes@santanderrio.com.ar', telefono: ''}], notas: ''},
            galicia: {id: 'galicia', nombre: 'Banco Galicia', categoria: 'financiero', queInformacion: ['Cuentas', 'Transacciones'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios', email: 'oficios.judiciales@bancogalicia.com.ar', telefono: ''}], notas: ''},

            // === REGISTROS ===
            nic: {id: 'nic', nombre: 'Nic Argentina', categoria: 'registros', queInformacion: ['Titularidad de dominios .ar', 'Historial de dominios'], requisitosLegales: ['Oficio Judicial'], procedimiento: 'Consultar web o enviar oficio físico/digital.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Mesa de Entradas', email: 'nic.ar', telefono: '011-5235-1166'}], notas: 'San Martín 536 Piso 1, CABA.'},
            aubasa: {id: 'aubasa', nombre: 'AUBASA', categoria: 'registros', queInformacion: ['Paso de peajes', 'Cámaras'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'legales@aubasa.com.ar', telefono: ''}], notas: ''}
        }
};
