/**
 * Catálogo ASOT: mapeos y fichas de organismos.
 * Editar este archivo para actualizar datos sin tocar la interfaz.
 */
window.ASOT_DATA = {
    datosAInformacion: {
            telefono: ['Registro de Llamadas', 'Geolocalización', 'Historial SMS', 'Información de suscriptor', 'Contactos/amigos', 'Métodos de pago asociados'],
            ip: ['Actividad de navegación', 'Identificación de usuario', 'ISP utilizado', 'Servicios accedidos', 'Historial de logins'],
            email: ['Información de cuenta', 'Historial de transacciones', 'Almacenamiento cloud', 'Actividad de login', 'Dispositivos asociados', 'Perfil de usuario'],
            cuenta_banco: ['Historial de transacciones', 'Saldos', 'Transferencias', 'Datos de registro', 'Identificación de entidad financiera'],
            usuario_redsocial: ['Perfil de usuario', 'Historial de accesos IP', 'Contenido público/privado', 'Mensajes directos', 'Lista de amigos'],
            vehiculo: ['Registración del vehículo', 'Datos de viaje/trayecto', 'Métodos de pago del conductor'],
            wallet_cripto: ['Datos de cuenta cripto (KYC)', 'Operaciones cripto'],
            dominio: ['Titularidad de dominio', 'Logs de acceso al panel del dominio']
        },
    informacionAServicios: {
            'Registro de Llamadas': ['movistar', 'personal', 'claro', 'tuenti', 'telecom'],
            'Geolocalización': ['movistar', 'personal', 'claro', 'google', 'apple', 'uber', 'cabify', 'didi'],
            'Historial SMS': ['movistar', 'personal', 'claro'],
            'Información de suscriptor': ['movistar', 'personal', 'claro', 'tuenti', 'telecom', 'fibertel', 'telecentro', 'telered', 'iplan', 'arlink', 'citilan', 'starlink', 'apple', 'google', 'netflix'],
            'Actividad de navegación': ['fibertel', 'telecentro', 'telered', 'iplan', 'arlink', 'citilan', 'starlink'],
            'Identificación de usuario': ['facebook', 'whatsapp', 'google', 'mercadolibre', 'twitter'],
            'Información de cuenta': ['google', 'facebook', 'apple', 'microsoft', 'yahoo', 'dropbox', 'spotify', 'zoom', 'personal_pay', 'airbnb', 'pedidosya', 'garmin'],
            'Perfil de usuario': ['facebook', 'tiktok', 'twitter', 'badoo', 'tinder', 'happn', 'snapchat', 'telegram', 'wechat', 'zangi', 'reddit'],
            'Historial de accesos IP': ['facebook', 'whatsapp', 'google', 'microsoft', 'mercadolibre', 'yahoo', 'netflix', 'sony', 'telegram', 'wechat', 'zangi', 'reddit'],
            'Historial de transacciones': ['mercadolibre', 'paypal', 'uala', 'personal_pay', 'santander', 'galicia', 'bna', 'provincia', 'apple', 'uber', 'bbva', 'brubank', 'ciudad', 'coinag', 'columbia', 'credicoop', 'macro', 'itau', 'bancor', 'blp', 'bsj', 'bsc', 'bsf', 'bvalores', 'modo', 'belo', 'n1u', 'naranjax', 'dolarapp', 'lemon', 'ripio', 'buenbit', 'fiwind', 'prisma', 'coelsa', 'amex', 'fiserv', 'wu', 'cencopay', 'airbnb', 'pedidosya'],
            'Datos de viaje/trayecto': ['uber', 'cabify', 'didi', 'aubasa'],
            'Métodos de pago del conductor': ['uber', 'cabify', 'didi', 'aubasa'],
            'Identificación de entidad financiera': ['bcra'],
            'Datos de cuenta cripto (KYC)': ['binance', 'coinbase', 'bitfinex', 'tether', 'kraken', 'huobi', 'okx', 'cryptocom', 'bitstamp', 'bitpanda', 'fixedfloat', 'bitso'],
            'Operaciones cripto': ['binance', 'coinbase', 'bitfinex', 'tether', 'kraken', 'huobi', 'okx', 'cryptocom', 'bitstamp', 'bitpanda', 'fixedfloat', 'bitso'],
            'Titularidad de dominio': ['nic', 'cloudflare', 'namecheap'],
            'Logs de acceso al panel del dominio': ['cloudflare', 'namecheap']
        },
    servicios: {
            // === TELECOMUNICACIONES ===
            claro: {id: 'claro', dominio: 'claro.com.ar', nombre: 'Claro (AMX Argentina)', categoria: 'telecomunicaciones', queInformacion: ['Titularidad', 'Registro de Llamadas', 'Geolocalización', 'SMS'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF por correo.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Oficina de Legales', email: 'oficiosjudiciales@claro.com.ar', telefono: '011-4109-8888'}], notas: 'Para IP dinámicas informan que no es posible determinar usuario sin puerto.'},
            personal: {id: 'personal', dominio: 'personal.com.ar', nombre: 'Telecom Personal', categoria: 'telecomunicaciones', queInformacion: ['Datos filiatorios del titular (líneas activas e inactivas)', 'Registro de llamadas entrantes/salientes', 'SMS en rango de fechas (dd/mm/aaaa – dd/mm/aaaa)', 'Celdas/Geolocalización de antenas (latitud, longitud, altitud, azimut)', 'Otras líneas activas del mismo titular', 'Recargas e identificación de quien abona la línea', 'IMEI y nuevas líneas vinculadas al mismo IMEI'], requisitosLegales: ['Oficio en hoja oficial, formato PDF', 'Firma digital identificable', 'Email institucional'], procedimiento: 'Personal Policial: enviar oficio PDF a requerimientosjudiciales@teco.com.ar. Fiscalías/Juzgados: vía DEOX o autogestionrp@teco.com.ar.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Email (Personal Policial)', email: 'requerimientosjudiciales@teco.com.ar', telefono: '0810-444-0222 (Opción 2 Fax)'}, {nombre: 'DEOX / Autogestión (Fiscalías)', email: 'autogestionrp@teco.com.ar', telefono: ''}], notas: 'Única empresa con acceso a NATEO/CGNAT (precisión de hora, minutos y segundos). No brindan info de WhatsApp, Geolocalización ni BackUps. No confundir con Telecom Argentina (fija).'},
            movistar: {id: 'movistar', dominio: 'movistar.com.ar', nombre: 'Movistar', categoria: 'telecomunicaciones', queInformacion: ['Datos filiatorios del titular (líneas activas e inactivas)', 'Registro de llamadas entrantes/salientes', 'SMS en rango de fechas (dd/mm/aaaa – dd/mm/aaaa)', 'Celdas/Geolocalización de antenas (latitud, longitud, altitud, azimut)', 'Otras líneas activas del mismo titular', 'Recargas e identificación de quien abona la línea', 'IMEI y nuevas líneas vinculadas al mismo IMEI'], requisitosLegales: ['Oficio en hoja oficial, formato PDF', 'Firma digital identificable', 'Email institucional (no cuentas particulares)'], procedimiento: 'Fiscalías/Juzgados: ingresar por portal web. Personal Policial: enviar oficio PDF por email institucional.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal (Fiscalías/Juzgados)', url: 'https://xwebexternos.movistar.com.ar/Jx3WebApp/Account/login', email: '', telefono: ''}, {nombre: 'Email (Personal Policial)', email: 'reqjudiciales.ar@telefonica.com', telefono: ''}], notas: 'Claves de portal gestionadas por Secretaría de Política Criminal. En intervenciones telefónicas contemplar también IMEI y nuevas líneas vinculadas (DAJUDECO).'},
            tuenti: {id: 'tuenti', dominio: 'tuenti.com', nombre: 'Tuenti', categoria: 'telecomunicaciones', queInformacion: ['Titularidad de línea'], requisitosLegales: ['Oficio PDF con firma digital'], procedimiento: 'Enviar oficio por email oficial.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Req. Judiciales', email: 'reqjudiciales@telefonica.com', telefono: ''}], notas: 'Pertenece al grupo Telefónica.'},
            telecom: {id: 'telecom', dominio: 'telecom.com.ar', nombre: 'Telecom Argentina (Fija)', categoria: 'telecomunicaciones', queInformacion: ['Titularidad', 'Llamadas', 'Datos'], requisitosLegales: ['Oficio PDF con firma digital'], procedimiento: 'Enviar PDF firmado.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Req. Judiciales', email: 'requerimientosjudiciales@teco.com.ar', telefono: ''}], notas: 'Aclarar período. No confundir con Telecom Personal.'},

            // === ISP ===
            fibertel: {id: 'fibertel', dominio: 'fibertel.com.ar', nombre: 'Fibertel - Cablevisión (Prima S.A.)', categoria: 'isp', queInformacion: ['Titularidad de IP', 'Registros de conexión'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Área de Legales', email: 'legalesoficios@cablevision.com.ar', telefono: '011-5530-6516'}], notas: 'CRÍTICO: Convertir huso horario a GMT-300 en el oficio si la IP se obtuvo de un servicio extranjero.'},
            telecentro: {id: 'telecentro', dominio: 'telecentro.com.ar', nombre: 'TeleCentro S.A.', categoria: 'isp', queInformacion: ['Titularidad de IP', 'Datos de cliente'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'IP Admin / Negocios', email: 'ipadmin@telecentro.net.ar', telefono: '011-4651-0084'}], notas: 'Con copia sugerida a negocios@telecentro.net.ar'},
            telered: {id: 'telered', dominio: 'telered.net.ar', nombre: 'TeleRed (Ver TV S.A.)', categoria: 'isp', queInformacion: ['Titularidad de IP'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Tecnología', email: 'tecnologia@telered.net.ar', telefono: '011-4469-7452'}], notas: ''},
            iplan: {id: 'iplan', dominio: 'iplan.net.ar', nombre: 'IPlan (NSS S.A.)', categoria: 'isp', queInformacion: ['Titularidad de IP'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Legales', email: 'legales@iplan.com.ar', telefono: ''}], notas: ''},

            // === PLATAFORMAS ===
            facebook: {id: 'facebook', dominio: 'facebook.com', nombre: 'Facebook / Instagram', categoria: 'plataformas', queInformacion: ['IP de conexión y logs de acceso', 'Geoposicionamiento de emergencia (azimut, longitud, latitud)', 'Datos de registración del usuario', 'Fecha de creación de cuenta', 'Correos electrónicos y teléfonos asociados', 'Preservación de información (90 días)'], requisitosLegales: ['Oficio firmado a mano alzada por Juez con sello medalla y sello personal, digitalizado a PDF', 'Email institucional obligatorio'], procedimiento: 'COURT ORDER: Cargar PDF en portal con email institucional. EMERGENCY (riesgo de vida inminente): Proceso especial sin oficio, requiere justificación de riesgo. Para contenido de mensajes se requiere Exhorto (MLAT).', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal Court Order', url: 'https://www.facebook.com/records/login/', email: '', telefono: ''}], notas: 'Identificar cuenta con: email, teléfono, ID numérico (facebook.com/profile.php?id=...) o nombre de usuario. Indicar expresamente si NO SE DEBE NOTIFICAR al usuario.'},
            whatsapp: {id: 'whatsapp', dominio: 'whatsapp.com', nombre: 'WhatsApp', categoria: 'plataformas', queInformacion: ['IP de conexión y logs de acceso', 'Geoposicionamiento de emergencia (azimut, longitud, latitud)', 'Datos de registración', 'Fecha de creación de cuenta', 'Teléfonos asociados', 'Preservación de información (90 días)'], requisitosLegales: ['Oficio firmado a mano alzada por Juez con sello medalla y sello personal, digitalizado a PDF', 'Email institucional obligatorio'], procedimiento: 'COURT ORDER: cargar PDF en portal. EMERGENCY (riesgo de vida inminente): proceso especial sin oficio. NO poseen contenido de mensajes (cifrado de extremo a extremo).', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal Court Order', url: 'https://www.whatsapp.com/records/login', email: '', telefono: ''}], notas: 'Petición de IP requiere fechas exactas. Identificar cuenta con: teléfono, email o ID de usuario. Indicar expresamente si NO SE DEBE NOTIFICAR al usuario.'},
            google: {id: 'google', dominio: 'google.com', nombre: 'Google', categoria: 'plataformas', queInformacion: ['IPs de sesión', 'Datos de suscriptor', 'Fecha de creación'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email oficial.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Global Law Enforcement', email: 'lis-global@google.com', telefono: ''}], notas: 'Incluir rango de fechas, URL/correo exacto y datos completos del requirente.'},
            mercadolibre: {id: 'mercadolibre', dominio: 'mercadolibre.com.ar', nombre: 'MercadoLibre / MercadoPago', categoria: 'plataformas', queInformacion: ['Usuarios asociados al DNI y estado (activo/inactivo)', 'Correos electrónicos asociados', 'Domicilios aportados', 'Teléfonos de contacto', 'Nombre y apellido vinculados', 'Entidades bancarias', 'Datos biométricos (foto de rostro y DNI)', 'IP/logs de conexión de registro y publicación', 'Publicaciones, ofertas, pagos y transferencias', 'Domicilio de envíos y geoposicionamiento de entrega', 'Empresa de entrega y código de rastreo', 'Datos del receptor y teléfono'], requisitosLegales: ['Oficio con firma digital', 'Email institucional'], procedimiento: 'Enviar PDF al correo de notificaciones. MercadoLibre (grupo amarillo) y MercadoPago (grupo celeste).', tiempoRespuesta: 'Rápido (Estándar) / Lento (Especial)', contactos: [{nombre: 'Notificaciones', email: 'notificaciones@mercadolibre.com', telefono: '011-4640-8000 int 8876'}], notas: 'Identificar por: Nickname, Email, Nro Publicación o Tarjeta (6 primeros + 4 últimos). Un mismo DNI puede tener varios usuarios con distintos emails.'},
            apple: {id: 'apple', dominio: 'apple.com', nombre: 'Apple', categoria: 'plataformas', queInformacion: ['Registro de dispositivos', 'iCloud', 'Compras iTunes', 'Conexiones IP'], requisitosLegales: ['Formulario de Apple PDF firmado'], procedimiento: 'Enviar formulario PDF a email. Tienen portal para congelamiento.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Law Enforcement', email: 'lawenforcement@apple.com', telefono: ''}, {nombre: 'Emergencias', email: 'exigent@apple.com', telefono: ''}], notas: 'Apple NOTIFICA al usuario salvo que la orden judicial lo prohíba expresamente.'},
            microsoft: {id: 'microsoft', dominio: 'microsoft.com', nombre: 'Microsoft (Hotmail, Xbox, Skype)', categoria: 'plataformas', queInformacion: ['Suscripción', 'Registro de IPs', 'Contactos'], requisitosLegales: ['Oficio firmado por Juez', 'Planilla Excel de Microsoft'], procedimiento: 'Enviar Oficio PDF + Planilla Excel. Asunto del correo estandarizado.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'LENS Team', email: 'asklcala@microsoft.com', telefono: ''}], notas: 'Asunto debe ser: PAIS - PROVINCIA - IPP/OFICIO.'},
            twitter: {id: 'twitter', dominio: 'x.com', nombre: 'Twitter', categoria: 'plataformas', queInformacion: ['Conservación de datos', 'Información de cuenta'], requisitosLegales: ['Oficio firmado por Juez'], procedimiento: 'Cargar a través del portal web.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal', url: 'https://legalrequests.twitter.com', email: '', telefono: ''}], notas: 'Buscar el User ID numérico oculto en el código fuente del perfil para asegurar el target.'},
            tiktok: {id: 'tiktok', dominio: 'tiktok.com', nombre: 'TikTok', categoria: 'plataformas', queInformacion: ['Usuario', 'Email/Tel', 'IP de creación', 'Logs de login'], requisitosLegales: ['Formulario TikTok firmado y sellado'], procedimiento: 'Completar DOCX de TikTok, pasar a PDF y enviar.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'legal@tiktok.com', telefono: ''}], notas: 'Videos privados requieren orden de búsqueda.'},
            netflix: {id: 'netflix', dominio: 'netflix.com', nombre: 'Netflix', categoria: 'plataformas', queInformacion: ['Email', 'Facturación', 'IPs de streaming', 'Dispositivos'], requisitosLegales: ['Formulario Netflix firmado por Juez con sellos'], procedimiento: 'Completar PDF de Netflix y enviar por correo.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal Process', email: 'legalprocess@netflix.com', telefono: ''}], notas: 'No guarda contenido, solo metadatos de conexión y pago.'},
            spotify: {id: 'spotify', dominio: 'spotify.com', nombre: 'Spotify', categoria: 'plataformas', queInformacion: ['IPs', 'Dispositivos', 'Ubicación no exacta', 'Datos de pago'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Support', email: 'support@spotify.com', telefono: ''}], notas: ''},
            zoom: {id: 'zoom', dominio: 'zoom.us', nombre: 'Zoom', categoria: 'plataformas', queInformacion: ['Datos dispositivo', 'IP', 'Tiempos de reunión'], requisitosLegales: ['Oficio PDF firmado digitalmente'], procedimiento: 'Enviar por correo. Es necesario el Email del titular de cuenta.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Law Enforcement', email: 'lawenforcement@zoom.us', telefono: ''}], notas: ''},
            dropbox: {id: 'dropbox', dominio: 'dropbox.com', nombre: 'Dropbox', categoria: 'plataformas', queInformacion: ['Nombre', 'Email', 'IPs de acceso', 'Dispositivo'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Compliance', email: 'legalcompliance@dropbox.com', telefono: ''}], notas: 'Urgencias agregar "EmergencyRequest" al Asunto.'},
            yahoo: {id: 'yahoo', dominio: 'yahoo.com', nombre: 'Yahoo / Flickr', categoria: 'plataformas', queInformacion: ['IPs de alta', 'Cuentas asociadas', 'Logs de correo/Messenger'], requisitosLegales: ['Oficio firmado'], procedimiento: 'Enviar PDF firmado digitalmente o vía portal Oath.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'ar-legalpoc@yahoo-inc.com', telefono: ''}], notas: 'Permiten congelamiento por 90 días.'},
            sony: {id: 'sony', dominio: 'playstation.com', nombre: 'Sony Playstation', categoria: 'plataformas', queInformacion: ['IPs de acceso', 'Cuentas', 'Transacciones'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'LE Requests', email: 'LE_legalrequests@playstation.sony.com', telefono: ''}], notas: 'Tracking ideal a través de compras en la tienda.'},
            airbnb: {id: 'airbnb', dominio: 'airbnb.com', nombre: 'Airbnb', categoria: 'plataformas', queInformacion: ['Datos de usuario', 'Reservas'], requisitosLegales: ['Oficio PDF firmado y sellado (Inglés)'], procedimiento: 'Cargar a través del portal de autoridades o email PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal', url: 'https://es.airbnb.com/lert', email: '', telefono: ''}, {nombre: 'Mail', email: 'leoinfo@airbnb.com', telefono: ''}], notas: 'Airbnb notifica al usuario salvo orden judicial contraria.'},
            badoo: {id: 'badoo', dominio: 'badoo.com', nombre: 'Badoo', categoria: 'plataformas', queInformacion: ['Datos de registro', 'Conexiones'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Llenar formulario en portal web y adjuntar PDF.', tiempoRespuesta: 'Hasta 30 días', contactos: [{nombre: 'Portal', url: 'https://badoo.com/es/team/contacts/', email: '', telefono: ''}], notas: 'Oficio debe contener ID de usuario o Email.'},
            tinder: {id: 'tinder', dominio: 'tinder.com', nombre: 'Match - Tinder', categoria: 'plataformas', queInformacion: ['Datos de registro', 'Conexiones'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: '', telefono: ''}], notas: 'Verificar email de contacto actualizado en el sitio oficial de Match Group.'},
            happn: {id: 'happn', dominio: 'happn.com', nombre: 'Happn', categoria: 'plataformas', queInformacion: ['Datos de registro'], requisitosLegales: ['Oficio en francés firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: '', telefono: ''}], notas: 'El oficio debe estar en francés. Verificar email de contacto actualizado en el sitio oficial de Happn.'},
            snapchat: {id: 'snapchat', dominio: 'snapchat.com', nombre: 'Snapchat', categoria: 'plataformas', queInformacion: ['Datos de registro'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'lawenforcement@snapchat.com', telefono: ''}], notas: 'Portal de urgencias disponible en lawenforcement.snapchat.com/emergency'},

            // === TRANSPORTE ===
            uber: {id: 'uber', dominio: 'uber.com', nombre: 'Uber', categoria: 'transporte', queInformacion: ['Perfil del usuario y datos filiatorios', 'Viajes en rango de fechas (vehículo, origen y destino)', 'Recorrido por geolocalización GPS', 'Método de pago (si tarjeta: número y entidad bancaria)', 'Servicios utilizados y datos cargados en la plataforma', 'IPs de acceso'], requisitosLegales: ['Oficio firmado por Juez con sellos', 'Email institucional'], procedimiento: 'Ingresar al portal LERT con email institucional y cargar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal LERT', url: 'https://www.lert.uber.com', email: '', telefono: ''}, {nombre: 'Email', email: 'LERT@uber.com', telefono: ''}], notas: 'Conservan registros por 90 días si se solicita. Pueden notificar al usuario/conductor.'},
            cabify: {id: 'cabify', dominio: 'cabify.com', nombre: 'Cabify', categoria: 'transporte', queInformacion: ['Datos de usuario', 'Viajes'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Cargar mediante el portal Jotform de Policía.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Info', email: 'info@cabify.com', telefono: ''}, {nombre: 'Portal', url: 'https://cabify.jotform.com', email: '', telefono: ''}], notas: ''},
            didi: {id: 'didi', dominio: 'didiglobal.com', nombre: 'DiDi', categoria: 'transporte', queInformacion: ['Datos del viaje y ruta', 'Audio grabado del viaje (si el usuario lo activó)', 'Datos del vehículo: placa, año, marca, modelo y color', 'Datos de registro del socio (conductor)', 'Datos de registro del usuario (pasajero)', 'Datos de registro del socio flotilla (dueño del vehículo, si aplica)', 'Otros viajes del socio/usuario con fechas y horas'], requisitosLegales: ['Oficio firmado y sellado por el responsable', 'Debe incluir: fecha, dependencia, número de investigación y tipo de delito'], procedimiento: 'Ingresar al portal LERT de DiDi o enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal LERT', url: 'http://lert.didiglobal.com/', email: '', telefono: ''}, {nombre: 'Email', email: 'lert@didiglobal.com', telefono: ''}], notas: 'Existen celulares de contacto para delitos flagrantes (Chile/Global).'},

            // === FINANCIERO ===
            uala: {id: 'uala', dominio: 'uala.com.ar', nombre: 'Ualá', categoria: 'financiero', queInformacion: ['Usuarios y estado (activo/inactivo)', 'Correos electrónicos asociados', 'Domicilios aportados', 'Teléfonos de contacto', 'Nombre y apellido vinculados', 'Entidades bancarias', 'IP/logs de conexión', 'Pagos, transferencias y movimientos de cuenta'], requisitosLegales: ['Oficio en hoja oficial, formato PDF', 'Firma digital identificable'], procedimiento: 'Enviar oficio PDF por email institucional.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'legales.ar@uala.com.ar', telefono: '011-52633563'}], notas: ''},
            personal_pay: {id: 'personal_pay', dominio: 'personalpay.com.ar', nombre: 'Personal Pay (Microsistemas S.A.U.)', categoria: 'financiero', queInformacion: ['Datos de registración: CUIL, email, fecha', 'Búsqueda por Alias, CVU, CUIL o domicilio informado', 'IP de creación de cuenta e IPs de conexión (compras, pagos)', 'Datos biométricos y foto de DNI', 'Movimientos de la cuenta'], requisitosLegales: ['Nota policial + oficio respaldatorio (delegación de Juez/Fiscal)', 'Firma digital identificable', 'Email institucional'], procedimiento: 'Enviar nota policial junto con oficio respaldatorio por email institucional.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Requerimientos', email: 'requerimientosPersonalPay@teco.com.ar', telefono: ''}], notas: 'Se puede identificar por Alias, CVU o CUIL. Incluye datos biométricos.'},
            paypal: {id: 'paypal', dominio: 'paypal.com', nombre: 'PayPal', categoria: 'financiero', queInformacion: ['Transacciones', 'Cuentas'], requisitosLegales: ['Oficio Judicial'], procedimiento: 'Cargar en portal SafetyHub.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Law Enforcement', email: 'lawenforcement@paypal.com', telefono: ''}], notas: 'Responderán solo a correos oficiales a través de su portal.'},
            bna: {id: 'bna', dominio: 'bna.com.ar', nombre: 'Banco Nación (BNA)', categoria: 'financiero', queInformacion: ['Cuentas', 'Cámaras de seguridad', 'Cajeros'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF. Hay correos específicos por sucursal (ej: 0094pop@bna.com.ar).', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios/Fraudes', email: 'operaciones-atm-analisisdefraudes@bna.com.ar', telefono: ''}, {nombre: 'Seguridad (Cámaras)', email: '', telefono: '011-4347-8644'}], notas: 'Para cámaras actuar rápidamente antes de sobrescritura.'},
            provincia: {id: 'provincia', dominio: 'bapro.com.ar', nombre: 'Banco Provincia (BAPRO)', categoria: 'financiero', queInformacion: ['Cuentas', 'Cámaras de seguridad'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Cámaras', email: 'cctvrescatefilmaciones@bpba.com.ar', telefono: '011-4309-3907 int 23907'}], notas: ''},
            santander: {id: 'santander', dominio: 'santander.com.ar', nombre: 'Santander', categoria: 'financiero', queInformacion: ['Cuentas', 'Transacciones'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios', email: 'oficiosdeinformes@santanderrio.com.ar', telefono: ''}], notas: ''},
            galicia: {id: 'galicia', dominio: 'galicia.com.ar', nombre: 'Banco Galicia', categoria: 'financiero', queInformacion: ['Cuentas', 'Transacciones'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios', email: 'oficios.judiciales@bancogalicia.com.ar', telefono: ''}], notas: ''},

            // === REGISTROS ===
            nic: {id: 'nic', dominio: 'nic.ar', nombre: 'Nic Argentina', categoria: 'registros', queInformacion: ['Titularidad de dominios .ar', 'Historial de dominios'], requisitosLegales: ['Oficio Judicial'], procedimiento: 'Consultar web o enviar oficio físico/digital.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Mesa de Entradas', url: 'https://www.nic.ar', email: '', telefono: '011-5235-1166'}], notas: 'San Martín 536 Piso 1, CABA.'},
            aubasa: {id: 'aubasa', dominio: 'aubasa.com.ar', nombre: 'AUBASA', categoria: 'registros', queInformacion: ['Paso de peajes', 'Cámaras'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'legales@aubasa.com.ar', telefono: ''}], notas: ''},

            // === TELECOMUNICACIONES (cont.) ===
            directv: {id: 'directv', dominio: 'directvla.com', nombre: 'DirecTV Argentina', categoria: 'telecomunicaciones', queInformacion: ['Titularidad de cuenta', 'Datos de instalación', 'Domicilio'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios Judiciales', email: 'oficiosjudiciales@directvla.com.ar', telefono: '011-3751-2428'}, {nombre: 'Legales', email: 'legales@directvla.com.ar', telefono: ''}], notas: 'TV satelital. Domicilio: Capitán Justo G. Bermúdez 4547, Complejo Lumina Panamericana, Torre I, Piso 1 — Munro, Vicente López, Bs.As.'},

            // === ISP (cont.) ===
            arlink: {id: 'arlink', dominio: 'superconectados.com.ar', nombre: 'Arlink / Supercanal / Superconectados', categoria: 'isp', queInformacion: ['Titularidad', 'Registros de conexión', 'Domicilio del cliente'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Rápida según relevamientos', contactos: [{nombre: 'Clientes', email: 'Clientes@superconectados.com.ar', telefono: ''}], notas: 'ISP de Mendoza y región. Arlink y Supercanal están asociados.'},
            citilan: {id: 'citilan', dominio: 'citilan.net', nombre: 'Citilan Argentina', categoria: 'isp', queInformacion: ['Titularidad de IP', 'Datos del cliente'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Información', email: 'info@citilan.net', telefono: ''}], notas: 'ISP de Buenos Aires.'},
            starlink: {id: 'starlink', dominio: 'starlink.com', nombre: 'Starlink (SpaceX)', categoria: 'isp', queInformacion: ['Titularidad de cuenta', 'IPs CGN asignadas con timestamp y puerto origen', 'Domicilio del kit', 'Logs de conexión'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF a starlinklawenforcement@spacex.com. Para urgencias usar starlinklawenforcementexigent@spacex.com.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Law Enforcement', email: 'starlinklawenforcement@spacex.com', telefono: ''}, {nombre: 'Urgencias', email: 'starlinklawenforcementexigent@spacex.com', telefono: ''}, {nombre: 'Privacidad', email: 'privacy@spacex.com', telefono: ''}], notas: 'Space Exploration Technologies, 1 Rocket Road, Hawthorne CA 90250. Usa IPv4 dinámicas CGN: requiere fecha/hora con zona horaria EXACTA, nº de puerto ORIGEN (no destino) e IP destino. Registros se conservan sólo 60 días.'},

            // === FINANCIERO — BANCOS (cont.) ===
            bcra: {id: 'bcra', dominio: 'bcra.gob.ar', nombre: 'BCRA - Banco Central', categoria: 'financiero', queInformacion: ['Listado de responsables de atención al cliente', 'Identificación de entidad financiera'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email. Listado público en bcra.gob.ar.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Consulta Oficios', email: 'consultaoficios@bcra.gob.ar', telefono: ''}, {nombre: 'Listado responsables', url: 'http://www.bcra.gob.ar/BCRAyVos/Responsables-Atencion-cliente-Bancos-companias-financieras.asp', email: '', telefono: ''}], notas: 'Publica el listado oficial de responsables de atención al cliente en bancos y financieras.'},
            bbva: {id: 'bbva', dominio: 'bbva.com', nombre: 'BBVA (Francés)', categoria: 'financiero', queInformacion: ['Titularidad de cuentas', 'Movimientos y transferencias', 'IPs de acceso a homebanking'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Mesa de Entradas', email: 'oficiomesaent.ar@bbva.com', telefono: '0800-333-0303'}, {nombre: 'Servicios Jurídicos', email: 'mesadeentradasserviciosjuridicos-arg@bbva.com', telefono: '011-4346-4800'}], notas: ''},
            brubank: {id: 'brubank', dominio: 'brubank.com', nombre: 'Brubank', categoria: 'financiero', queInformacion: ['Titularidad', 'Movimientos', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'legales@brubank.com', telefono: ''}], notas: ''},
            ciudad: {id: 'ciudad', dominio: 'bancociudad.com.ar', nombre: 'Banco Ciudad', categoria: 'financiero', queInformacion: ['Titularidad', 'Movimientos', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios Judiciales', email: 'oficiosjudiciales@bancociudad.com.ar', telefono: ''}], notas: ''},
            coinag: {id: 'coinag', dominio: 'bancocoinag.com', nombre: 'Banco Coinag', categoria: 'financiero', queInformacion: ['Titularidad', 'Movimientos', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'legales@bancocoinag.com', telefono: ''}, {nombre: 'Consultas y Reclamos', email: 'consultasyreclamos@bancocoinag.com', telefono: ''}], notas: ''},
            columbia: {id: 'columbia', dominio: 'bancocolumbia.com.ar', nombre: 'Banco Columbia', categoria: 'financiero', queInformacion: ['Titularidad', 'Movimientos', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Notificaciones Electrónicas', email: 'notificaciones_electronicas@bancocolumbia.com.ar', telefono: ''}], notas: ''},
            credicoop: {id: 'credicoop', dominio: 'bancocredicoop.coop', nombre: 'Banco Credicoop', categoria: 'financiero', queInformacion: ['Titularidad', 'Movimientos', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Gerencia Legales', email: 'gerleglegales@bancocredicoop.coop', telefono: ''}, {nombre: 'Mesa de Oficios', email: 'meoficios@bancocredicoop.coop', telefono: ''}], notas: ''},
            bancor: {id: 'bancor', dominio: 'bancor.com.ar', nombre: 'Banco de Córdoba (Bancor)', categoria: 'financiero', queInformacion: ['Titularidad', 'Movimientos', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Mesa General de Entradas', email: 'MesaGeneraldeEntradas@bancor.com.ar', telefono: '0351-420-7200 int. 7202'}], notas: 'Domicilio: Buenos Aires 147, 4° piso, Córdoba.'},
            blp: {id: 'blp', dominio: 'blp.com.ar', nombre: 'Banco de La Pampa', categoria: 'financiero', queInformacion: ['Titularidad', 'Movimientos', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'alegales@blp.com.ar', telefono: ''}], notas: ''},
            bsj: {id: 'bsj', dominio: 'bancosanjuan.com', nombre: 'Banco de San Juan', categoria: 'financiero', queInformacion: ['Titularidad', 'Movimientos', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Órdenes Judiciales', email: 'ordenesjudiciales@bancosanjuan.com', telefono: ''}], notas: ''},
            bsc: {id: 'bsc', dominio: 'bancosantacruz.com', nombre: 'Banco de Santa Cruz', categoria: 'financiero', queInformacion: ['Titularidad', 'Movimientos', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios Judiciales', email: 'oficiosjudicialessantacruz@bancosantacruz.com', telefono: ''}], notas: ''},
            bsf: {id: 'bsf', dominio: 'bancobsf.com.ar', nombre: 'Banco Santa Fe', categoria: 'financiero', queInformacion: ['Titularidad', 'Movimientos', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios Judiciales', email: 'oficiosjudiciales@bancobsf.com.ar', telefono: ''}], notas: ''},
            bvalores: {id: 'bvalores', dominio: 'bancodevalores.com', nombre: 'Banco de Valores', categoria: 'financiero', queInformacion: ['Titularidad', 'Movimientos', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'legales@bancodevalores.com', telefono: ''}], notas: ''},
            itau: {id: 'itau', dominio: 'itau.com.ar', nombre: 'Itaú Argentina', categoria: 'financiero', queInformacion: ['Titularidad', 'Movimientos', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios Judiciales', email: 'grupo_oficios_judiciales@itau.com.ar', telefono: '011-4378-8400 int. 8300'}], notas: 'Adquirido por Banco Macro.'},
            macro: {id: 'macro', dominio: 'macro.com.ar', nombre: 'Banco Macro', categoria: 'financiero', queInformacion: ['Titularidad', 'Movimientos', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios Judiciales', email: 'oficiosjudiciales@macro.com.ar', telefono: ''}, {nombre: 'Legales Banca', email: 'legalesbanca@grupomacro.com.ar', telefono: ''}], notas: ''},

            // === FINANCIERO — BILLETERAS VIRTUALES (cont.) ===
            naranjax: {id: 'naranjax', dominio: 'naranjax.com', nombre: 'Naranja X', categoria: 'financiero', queInformacion: ['Titularidad y datos de registro', 'Movimientos y transferencias', 'Datos de tarjeta de crédito física asociada', 'IPs de conexión'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Cargar oficio en el portal de justicia.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal Justicia', url: 'https://operation.naranjax.com/justicia', email: '', telefono: ''}], notas: 'Brinda info tanto de la billetera virtual como de la tarjeta de crédito física.'},
            modo: {id: 'modo', dominio: 'modo.com.ar', nombre: 'MODO', categoria: 'financiero', queInformacion: ['Titularidad y datos de registro', 'Movimientos y transferencias', 'CVU/alias y métodos de pago vinculados', 'IPs de conexión'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Notificaciones Judiciales', email: 'notificaciones.judiciales@modo.com.ar', telefono: ''}, {nombre: 'Oficios', email: 'oficios@modo.com.ar', telefono: ''}], notas: 'MODO es la billetera de los bancos.'},
            belo: {id: 'belo', dominio: 'belo.app', nombre: 'Belo', categoria: 'financiero', queInformacion: ['Titularidad y datos KYC', 'Movimientos y transferencias', 'CVU/alias', 'IPs de conexión'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email. Compliance suele responder más rápido.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Contacto Legal', email: 'contactolegal@belo.app', telefono: ''}, {nombre: 'Compliance', email: 'compliance@belo.app', telefono: ''}], notas: 'Razón social: Belo Cash S.A.'},
            lemon: {id: 'lemon', dominio: 'lemon.me', nombre: 'Lemon Cash', categoria: 'financiero', queInformacion: ['Titularidad y datos KYC', 'Movimientos y transferencias', 'IPs de conexión'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email o usar formulario de soporte.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Soporte', email: 'soporte@lemon.me', telefono: ''}, {nombre: 'Formulario', url: 'https://form.jotform.com/231774405436659', email: '', telefono: ''}], notas: 'Empresa relocalizada a El Salvador.'},
            ripio: {id: 'ripio', dominio: 'ripio.com', nombre: 'Ripio / DigiPayments', categoria: 'financiero', queInformacion: ['Titularidad y datos KYC', 'Movimientos', 'IPs de conexión'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Prevención de Fraude', email: 'prevencion@ripio.com', telefono: ''}], notas: ''},
            buenbit: {id: 'buenbit', dominio: 'buenbit.com', nombre: 'Buenbit', categoria: 'financiero', queInformacion: ['Titularidad y datos KYC', 'Movimientos', 'IPs de conexión'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'legales@buenbit.com', telefono: ''}, {nombre: 'Soporte', email: 'soporte@buenbit.com', telefono: ''}], notas: ''},
            fiwind: {id: 'fiwind', dominio: 'fiwind.io', nombre: 'Fiwind', categoria: 'financiero', queInformacion: ['Titularidad y datos KYC', 'Movimientos', 'IPs de conexión'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Rápida (~2 horas si se envía temprano)', contactos: [{nombre: 'Legales', email: 'legales@fiwind.io', telefono: ''}], notas: 'Razón social: Fiwind Pay S.A.'},
            dolarapp: {id: 'dolarapp', dominio: 'dolarapp.com', nombre: 'Dolar App (GARPA S.A.)', categoria: 'financiero', queInformacion: ['Titularidad y datos KYC', 'Movimientos', 'IPs de conexión'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Help', email: 'help@dolarapp.com', telefono: ''}], notas: 'Razón social informada por COELSA: GARPA S.A.'},
            n1u: {id: 'n1u', dominio: 'n1u.app', nombre: 'N1U', categoria: 'financiero', queInformacion: ['Titularidad y datos KYC', 'Movimientos', 'IPs de conexión'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Ayuda', email: 'ayuda@n1u.app', telefono: '11-2525-2222 (WhatsApp)'}], notas: ''},

            // === MEDIOS DE PAGO ===
            prisma: {id: 'prisma', dominio: 'prismamp.com', nombre: 'Prisma Medios de Pago', categoria: 'medios_pago', queInformacion: ['Datos de transacciones', 'Identificación de comercio', 'Datos del titular de tarjeta', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios Judiciales', email: 'oficiosjudiciales@prismamp.com', telefono: ''}], notas: 'Procesa Visa y Mastercard. A este correo se deriva lo que antes se pedía directo a Mastercard.'},
            coelsa: {id: 'coelsa', dominio: 'coelsa.com.ar', nombre: 'COELSA — Cámara Compensadora', categoria: 'medios_pago', queInformacion: ['Identificación de PSP detrás de un CVU/alias', 'Datos de transacciones interbancarias'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios Legales', email: 'oficioslegales@coelsa.com.ar', telefono: ''}], notas: 'Resuelve consultas sobre qué PSP está detrás de un CVU/alias. Ej: informaron que "GARPA S.A." = Dolar App.'},
            amex: {id: 'amex', dominio: 'americanexpress.com', nombre: 'American Express (AMEX)', categoria: 'medios_pago', queInformacion: ['Datos de transacciones', 'Datos del titular de tarjeta', 'IPs de acceso'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF al SRU (Subpoena Response Unit). Aceptan vía CT Corp, fax o correo postal.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'SRU', email: 'amexsru@aexp.com', telefono: '888-257-7775'}, {nombre: 'Global Security', email: 'global.security.comm.squad@aexp.com', telefono: ''}, {nombre: 'Portal SRU', url: 'https://www.americanexpress.com/en-us/company/legal/subpoena-response-unit/', email: '', telefono: ''}], notas: 'Subpoena Response Unit, 43 Butterfield Circle, El Paso, TX 79906, USA. Fax: (772) 360-4756.'},
            fiserv: {id: 'fiserv', dominio: 'fiserv.com', nombre: 'Fiserv (Pago Fácil)', categoria: 'medios_pago', queInformacion: ['Datos de transacciones', 'Identificación de comercio', 'Datos del titular'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Defensa del Consumidor', email: 'Defensa-del-consumidor@fiserv.com', telefono: ''}], notas: 'Procesa Pago Fácil.'},
            wu: {id: 'wu', dominio: 'westernunion.com', nombre: 'Western Union Argentina', categoria: 'medios_pago', queInformacion: ['Datos de remesas', 'Datos del remitente y receptor', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'legales@westernunion.com', telefono: ''}], notas: 'También aplica a Pago Fácil / Western Union.'},
            cencopay: {id: 'cencopay', dominio: 'cencopay.ar', nombre: 'Cencosud / Cencopay', categoria: 'medios_pago', queInformacion: ['Datos de transacciones', 'Datos del titular de tarjeta retail', 'IPs de acceso'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Atención Servicios Financieros', email: 'atencionserviciosfinancieros@cencosud.com.ar', telefono: '0810-9999-627'}, {nombre: 'Información', email: 'info@cencosud.com', telefono: ''}], notas: ''},

            // === CRIPTOMONEDAS ===
            binance: {id: 'binance', dominio: 'binance.com', nombre: 'Binance', categoria: 'cripto', queInformacion: ['Datos de registro KYC', 'Historial de operaciones', 'IPs de acceso', 'Direcciones de wallets', 'Métodos de fondeo y retiro'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Casos LE', email: 'case@binance.com', telefono: ''}, {nombre: 'Legal', email: 'legal@binance.com', telefono: ''}], notas: ''},
            coinbase: {id: 'coinbase', dominio: 'coinbase.com', nombre: 'Coinbase', categoria: 'cripto', queInformacion: ['Datos de registro KYC', 'Historial de operaciones', 'IPs de acceso', 'Direcciones de wallets'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Subpoenas', email: 'subpoenas@coinbase.com', telefono: ''}], notas: ''},
            bitfinex: {id: 'bitfinex', dominio: 'bitfinex.com', nombre: 'Bitfinex', categoria: 'cripto', queInformacion: ['Datos de registro KYC', 'Historial de operaciones', 'IPs de acceso', 'Direcciones de wallets'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Information Requests', email: 'inforequests@bitfinex.com', telefono: ''}], notas: ''},
            tether: {id: 'tether', dominio: 'tether.to', nombre: 'Tether', categoria: 'cripto', queInformacion: ['Datos de cuenta', 'Movimientos USDT', 'Direcciones de wallets'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Information Requests', email: 'inforequests@tether.to', telefono: ''}], notas: ''},
            kraken: {id: 'kraken', dominio: 'kraken.com', nombre: 'Kraken (Payward Inc.)', categoria: 'cripto', queInformacion: ['Datos de registro KYC', 'Historial de operaciones', 'IPs de acceso', 'Direcciones de wallets'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'legal@kraken.com', telefono: ''}, {nombre: 'Soporte', email: 'support@kraken.com', telefono: ''}], notas: 'Payward Ventures Inc., 237 Kearny Street #102, San Francisco, CA 94108, USA.'},
            huobi: {id: 'huobi', dominio: 'huobi.com', nombre: 'Huobi', categoria: 'cripto', queInformacion: ['Datos de registro KYC', 'Historial de operaciones', 'IPs de acceso'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Soporte', email: 'support@huobi.com', telefono: ''}], notas: ''},
            okx: {id: 'okx', dominio: 'okx.com', nombre: 'OKX (OKEx Seychelles)', categoria: 'cripto', queInformacion: ['Datos de registro KYC', 'Historial de operaciones', 'IPs de acceso'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Law Enforcement', email: 'LE_OKExSeychelles@okex.com', telefono: ''}], notas: 'Sociedad: OKEx Seychelles.'},
            cryptocom: {id: 'cryptocom', dominio: 'crypto.com', nombre: 'Crypto.com', categoria: 'cripto', queInformacion: ['Datos de registro KYC', 'Historial de operaciones', 'IPs de acceso'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Law Enforcement Global', email: 'lawenforcementglobal@crypto.com', telefono: ''}, {nombre: 'Contacto General', email: 'contact@crypto.com', telefono: ''}], notas: ''},
            bitstamp: {id: 'bitstamp', dominio: 'bitstamp.net', nombre: 'Bitstamp', categoria: 'cripto', queInformacion: ['Datos de registro KYC', 'Historial de operaciones', 'IPs de acceso'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Complaints', email: 'complaints@bitstamp.net', telefono: ''}], notas: ''},
            bitpanda: {id: 'bitpanda', dominio: 'bitpanda.com', nombre: 'Bitpanda', categoria: 'cripto', queInformacion: ['Datos de registro KYC', 'Historial de operaciones', 'IPs de acceso'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Soporte', email: 'support@bitpanda.zendesk.com', telefono: ''}], notas: ''},
            fixedfloat: {id: 'fixedfloat', dominio: 'fixedfloat.com', nombre: 'FixedFloat', categoria: 'cripto', queInformacion: ['Datos del pedido y wallet origen/destino', 'Logs de servidor', 'IPs de acceso'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF indicando "Director de FixedFloat" en el documento. Las transacciones y wallets deben ir en texto adjunto.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Información', email: 'info@fixedfloat.com', telefono: ''}], notas: 'Conservan registros del servidor y datos de pedidos. Piden formato específico en el oficio.'},
            bitso: {id: 'bitso', dominio: 'bitso.com', nombre: 'Bitso (México)', categoria: 'cripto', queInformacion: ['Datos de registro KYC', 'Historial de operaciones', 'IPs de acceso'], requisitosLegales: ['Tratado de Asistencia Mutua (MLAT) / Exhorto internacional'], procedimiento: 'Gestionar por Ministerio de Relaciones Exteriores como exhorto internacional.', tiempoRespuesta: 'Lenta (vía MLAT)', contactos: [{nombre: 'Vía Cancillería', url: 'https://www.cancilleria.gob.ar/', email: '', telefono: ''}], notas: 'Responden SOLO a Tratados de Asistencia Mutua. No reciben oficios directos.'},

            // === PLATAFORMAS (cont.) ===
            telegram: {id: 'telegram', dominio: 'telegram.org', nombre: 'Telegram', categoria: 'plataformas', queInformacion: ['ID de cuenta', 'Username', 'Teléfono asociado', 'IPs con timestamp'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF a dsa.telegram@edsr.eu — desde ahí se reenvía internamente.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'DSA EDSR', email: 'dsa.telegram@edsr.eu', telefono: ''}, {nombre: 'Content Referral', email: 'la-content-referral-dsa@telegram.org', telefono: ''}], notas: 'Devuelve: ID de cuenta, username, nº de teléfono e IP con timestamp.'},
            reddit: {id: 'reddit', dominio: 'reddit.com', nombre: 'Reddit', categoria: 'plataformas', queInformacion: ['Datos de cuenta', 'IPs de acceso', 'Logs de actividad'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Cargar la solicitud en el portal oficial de solicitudes legales.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal Solicitudes Legales', url: 'https://legalrequests.reddithelp.com/hc/en-us/requests/new?ticket_form_id=21279760653979', email: '', telefono: ''}], notas: ''},
            wechat: {id: 'wechat', dominio: 'wechat.com', nombre: 'WeChat', categoria: 'plataformas', queInformacion: ['Datos de cuenta', 'IPs de acceso'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Cargar la solicitud en el portal oficial de Law Enforcement.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal LE', url: 'https://www.wechat.com/es/law_enforcement_data_request.html', email: '', telefono: ''}], notas: ''},
            zangi: {id: 'zangi', dominio: 'zangi.com', nombre: 'Zangi', categoria: 'plataformas', queInformacion: ['Datos de cuenta', 'IPs de acceso'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar a legal@ con copia obligatoria a support@.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'legal@zangi.com', telefono: ''}, {nombre: 'Soporte (CC)', email: 'support@zangi.com', telefono: ''}], notas: 'App de mensajería de origen armenio. Todas las solicitudes deben enviarse a legal@ con copia a support@.'},
            cloudflare: {id: 'cloudflare', dominio: 'cloudflare.com', nombre: 'Cloudflare', categoria: 'plataformas', queInformacion: ['Titular del recurso/dominio', 'Logs de acceso e IPs', 'Información de pago/registro'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email. Para emergencias (delitos en curso) llamar.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Abuse Law', email: 'abuse+law@cloudflare.com', telefono: ''}, {nombre: 'Emergencias', email: '', telefono: '+1-415-713-9307'}], notas: 'CloudFlare Inc., 101 Townsend St, San Francisco, CA 94107, USA. Notifica al usuario salvo orden 2705(b).'},
            namecheap: {id: 'namecheap', dominio: 'namecheap.com', nombre: 'Namecheap', categoria: 'plataformas', queInformacion: ['Titular del dominio', 'Datos de registro y pago', 'IPs de acceso'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'Legal@namecheap.com', telefono: ''}, {nombre: 'Portal UDRP', url: 'https://www.namecheap.com/legal/domains/udrp/', email: '', telefono: ''}], notas: 'Registro de dominios extranjero (similar a NIC.ar).'},
            garmin: {id: 'garmin', dominio: 'garmin.com', nombre: 'Garmin', categoria: 'plataformas', queInformacion: ['Datos de cuenta y dispositivo', 'Geolocalización', 'Historial de actividad'], requisitosLegales: ['Oficio firmado por Juez', 'Recomendado en inglés', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Solicitud de Emergencia', email: 'legalemergencyrequest@garmin.com', telefono: ''}], notas: 'Correo válido para solicitudes de emergencia.'},

            // === TRANSPORTE (cont.) ===
            pedidosya: {id: 'pedidosya', dominio: 'pedidosya.com', nombre: 'PedidosYa', categoria: 'transporte', queInformacion: ['Datos del usuario', 'Historial de pedidos', 'Direcciones de entrega', 'Métodos de pago vinculados'], requisitosLegales: ['Oficio firmado digitalmente', 'Email institucional'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Contacto', email: 'contacto@pedidosya.com', telefono: ''}], notas: ''}
        },
    datosDisponibles: [
        { id: 'telefono',          label: 'Número de teléfono',           emoji: '☎️' },
        { id: 'ip',                label: 'Dirección IP',                 emoji: '🌐' },
        { id: 'email',             label: 'Email',                        emoji: '📧' },
        { id: 'cuenta_banco',      label: 'Cuenta bancaria / Tarjeta',    emoji: '🏦' },
        { id: 'usuario_redsocial', label: 'Usuario red social / Nickname', emoji: '📱' },
        { id: 'vehiculo',          label: 'Patente vehículo',             emoji: '🚗' },
        { id: 'wallet_cripto',     label: 'Wallet / Dirección cripto',    emoji: '🪙' },
        { id: 'dominio',           label: 'Dominio web',                  emoji: '🔗' }
    ],
    categorias: [
        { id: 'telecomunicaciones', label: 'Telecomunicaciones',  labelCorto: 'Telecom',     emoji: '📞' },
        { id: 'isp',                label: 'ISP (Internet)',      labelCorto: 'ISP',         emoji: '🌐' },
        { id: 'plataformas',        label: 'Plataformas y Redes', labelCorto: 'Plataforma',  emoji: '📱' },
        { id: 'transporte',         label: 'Transporte',          labelCorto: 'Transporte',  emoji: '🚗' },
        { id: 'financiero',         label: 'Financiero y Bancos', labelCorto: 'Financiero',  emoji: '🏦' },
        { id: 'medios_pago',        label: 'Medios de Pago',      labelCorto: 'Medios pago', emoji: '💳' },
        { id: 'cripto',             label: 'Criptomonedas',       labelCorto: 'Cripto',      emoji: '🪙' },
        { id: 'registros',          label: 'Registros',           labelCorto: 'Registro',    emoji: '📋' }
    ]
};

