/**
 * Catálogo ASOT: mapeos y fichas de organismos.
 * Editar este archivo para actualizar datos sin tocar la interfaz.
 */
window.ASOT_DATA = {
    datosAInformacion: {
            telefono: ['Registro de Llamadas', 'Geolocalización', 'Historial SMS', 'Información de suscriptor', 'Contactos/amigos', 'Métodos de pago asociados'],
            ip: ['Actividad de navegación', 'Identificación de usuario', 'ISP utilizado', 'Servicios accedidos', 'Historial de logins'],
            email: ['Información de cuenta', 'Historial de transacciones', 'Almacenamiento cloud', 'Actividad de login', 'Dispositivos asociados', 'Perfil de usuario'],
            cuenta_banco: ['Historial de transacciones', 'Saldos', 'Transferencias', 'Datos de registro'],
            usuario_redsocial: ['Perfil de usuario', 'Historial de accesos IP', 'Contenido público/privado', 'Mensajes directos', 'Lista de amigos'],
            vehiculo: ['Registración del vehículo', 'Datos de viaje/trayecto', 'Métodos de pago del conductor']
        },
    informacionAServicios: {
            'Registro de Llamadas': ['movistar', 'personal', 'claro', 'tuenti'],
            'Geolocalización': ['movistar', 'personal', 'claro', 'google', 'apple', 'uber', 'cabify', 'didi'],
            'Historial SMS': ['movistar', 'personal', 'claro'],
            'Información de suscriptor': ['movistar', 'personal', 'claro', 'fibertel', 'telecentro', 'apple', 'google', 'netflix'],
            'Actividad de navegación': ['fibertel', 'telecentro', 'telered', 'iplan'],
            'Identificación de usuario': ['facebook', 'whatsapp', 'google', 'mercadolibre', 'twitter'],
            'Información de cuenta': ['google', 'facebook', 'apple', 'microsoft', 'yahoo', 'dropbox', 'spotify', 'zoom', 'personal_pay'],
            'Perfil de usuario': ['facebook', 'tiktok', 'twitter', 'badoo', 'tinder', 'happn', 'snapchat'],
            'Historial de accesos IP': ['facebook', 'whatsapp', 'google', 'microsoft', 'mercadolibre', 'yahoo', 'netflix', 'sony'],
            'Historial de transacciones': ['mercadolibre', 'paypal', 'uala', 'personal_pay', 'santander', 'galicia', 'bna', 'provincia', 'apple', 'uber'],
            'Datos de viaje/trayecto': ['uber', 'cabify', 'didi'],
            'Métodos de pago del conductor': ['uber', 'cabify', 'didi']
        },
    servicios: {
            // === TELECOMUNICACIONES ===
            claro: {id: 'claro', dominio: 'claro.com.ar', nombre: 'Claro (AMX Argentina)', categoria: 'telecomunicaciones', queInformacion: ['Titularidad', 'Registro de Llamadas', 'Geolocalización', 'SMS'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF por correo.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Oficina de Legales', email: 'oficiosjudiciales@claro.com.ar', telefono: '011-4109-8888'}], notas: 'Para IP dinámicas informan que no es posible determinar usuario sin puerto.'},
            personal: {id: 'personal', dominio: 'personal.com.ar', nombre: 'Telecom Personal', categoria: 'telecomunicaciones', queInformacion: ['Datos filiatorios del titular (líneas activas e inactivas)', 'Registro de llamadas entrantes/salientes', 'SMS en rango de fechas (dd/mm/aaaa – dd/mm/aaaa)', 'Celdas/Geolocalización de antenas (latitud, longitud, altitud, azimut)', 'Otras líneas activas del mismo titular', 'Recargas e identificación de quien abona la línea', 'IMEI y nuevas líneas vinculadas al mismo IMEI'], requisitosLegales: ['Oficio en hoja oficial, formato PDF', 'Firma digital identificable', 'Email institucional'], procedimiento: 'Personal Policial: enviar oficio PDF a requerimientosjudiciales@teco.com.ar. Fiscalías/Juzgados: vía DEOX o autogestionrp@teco.com.ar.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Email (Personal Policial)', email: 'requerimientosjudiciales@teco.com.ar', telefono: '0810-444-0222 (Opción 2 Fax)'}, {nombre: 'DEOX / Autogestión (Fiscalías)', email: 'autogestionrp@teco.com.ar', telefono: ''}], notas: 'Única empresa con acceso a NATEO/CGNAT (precisión de hora, minutos y segundos). No brindan info de WhatsApp, Geolocalización ni BackUps. No confundir con Telecom Argentina (fija).'},
            movistar: {id: 'movistar', dominio: 'movistar.com.ar', nombre: 'Movistar', categoria: 'telecomunicaciones', queInformacion: ['Datos filiatorios del titular (líneas activas e inactivas)', 'Registro de llamadas entrantes/salientes', 'SMS en rango de fechas (dd/mm/aaaa – dd/mm/aaaa)', 'Celdas/Geolocalización de antenas (latitud, longitud, altitud, azimut)', 'Otras líneas activas del mismo titular', 'Recargas e identificación de quien abona la línea', 'IMEI y nuevas líneas vinculadas al mismo IMEI'], requisitosLegales: ['Oficio en hoja oficial, formato PDF', 'Firma digital identificable', 'Email institucional (no cuentas particulares)'], procedimiento: 'Fiscalías/Juzgados: ingresar por portal web. Personal Policial: enviar oficio PDF por email institucional.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal (Fiscalías/Juzgados)', url: 'https://xwebexternos.movistar.com.ar/Jx3WebApp/Account/login', email: '', telefono: ''}, {nombre: 'Email (Personal Policial)', email: 'reqjudiciales.ar@telefonica.com', telefono: ''}], notas: 'Claves de portal gestionadas por Secretaría de Política Criminal. En intervenciones telefónicas contemplar también IMEI y nuevas líneas vinculadas (DAJUDECO).'},
            tuenti: {id: 'tuenti', dominio: 'tuenti.com', nombre: 'Tuenti', categoria: 'telecomunicaciones', queInformacion: ['Titularidad de línea'], requisitosLegales: ['Oficio PDF con firma digital'], procedimiento: 'Enviar oficio por email oficial.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Req. Judiciales', email: 'reqjudiciales@telefonica.com', telefono: ''}], notas: 'Pertenece al grupo Telefónica.'},
            telecom: {id: 'telecom', dominio: 'telecom.com.ar', nombre: 'Telecom Argentina (Fija)', categoria: 'telecomunicaciones', queInformacion: ['Titularidad', 'Llamadas', 'Datos'], requisitosLegales: ['Oficio PDF con firma digital'], procedimiento: 'Enviar PDF firmado.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Req. Judiciales', email: 'requerimientosjudiciales@teco.com.ar', telefono: ''}], notas: 'Aclarar período. No confundir con Telecom Personal.'},

            // === ISP ===
            fibertel: {id: 'fibertel', dominio: 'fibertel.com.ar', nombre: 'Fibertel - Cablevisión (Prima S.A.)', categoria: 'isp', queInformacion: ['Titularidad de IP', 'Registros de conexión'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Yamila Leigovich', email: 'legalesoficios@cablevision.com.ar', telefono: '011-5530-6516'}], notas: 'CRÍTICO: Convertir huso horario a GMT-300 en el oficio si la IP se obtuvo de un servicio extranjero.'},
            telecentro: {id: 'telecentro', dominio: 'telecentro.com.ar', nombre: 'TeleCentro S.A.', categoria: 'isp', queInformacion: ['Titularidad de IP', 'Datos de cliente'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'IP Admin / Negocios', email: 'ipadmin@telecentro.net.ar', telefono: '011-4651-0084'}], notas: 'Con copia sugerida a negocios@telecentro.net.ar'},
            telered: {id: 'telered', dominio: 'telered.net.ar', nombre: 'TeleRed (Ver TV S.A.)', categoria: 'isp', queInformacion: ['Titularidad de IP'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Tecnología', email: 'tecnologia@telered.net.ar', telefono: '011-4469-7452'}], notas: 'Copiar a acuadrado, ddonantueno, mcoingrate @telered.net.ar'},
            iplan: {id: 'iplan', dominio: 'iplan.net.ar', nombre: 'IPlan (NSS S.A.)', categoria: 'isp', queInformacion: ['Titularidad de IP'], requisitosLegales: ['Oficio Judicial con firma digital'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'No especificado', contactos: [{nombre: 'Legales', email: 'legales@iplan.com.ar', telefono: ''}], notas: ''},

            // === PLATAFORMAS ===
            facebook: {id: 'facebook', dominio: 'facebook.com', nombre: 'Facebook / Instagram', categoria: 'plataformas', queInformacion: ['IP de conexión y logs de acceso', 'Geoposicionamiento de emergencia (azimut, longitud, latitud)', 'Datos de registración del usuario', 'Fecha de creación de cuenta', 'Correos electrónicos y teléfonos asociados', 'Preservación de información (90 días)'], requisitosLegales: ['Oficio firmado a mano alzada por Juez con sello medalla y sello personal, digitalizado a PDF', 'Email institucional obligatorio'], procedimiento: 'COURT ORDER: Cargar PDF en portal con email institucional. EMERGENCY (riesgo de vida inminente): Proceso especial sin oficio, requiere justificación de riesgo. Para contenido de mensajes se requiere Exhorto (MLAT).', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal Court Order', url: 'https://www.facebook.com/records/login/', email: '', telefono: ''}], notas: 'Identificar cuenta con: email, teléfono, ID numérico (facebook.com/profile.php?id=...) o nombre de usuario. Indicar expresamente si NO SE DEBE NOTIFICAR al usuario.'},
            whatsapp: {id: 'whatsapp', dominio: 'whatsapp.com', nombre: 'WhatsApp', categoria: 'plataformas', queInformacion: ['IP de conexión y logs de acceso', 'Geoposicionamiento de emergencia (azimut, longitud, latitud)', 'Datos de registración', 'Fecha de creación de cuenta', 'Teléfonos asociados', 'Preservación de información (90 días)'], requisitosLegales: ['Oficio firmado a mano alzada por Juez con sello medalla y sello personal, digitalizado a PDF', 'Email institucional obligatorio'], procedimiento: 'COURT ORDER: cargar PDF en portal. EMERGENCY (riesgo de vida inminente): proceso especial sin oficio. NO poseen contenido de mensajes (cifrado de extremo a extremo).', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal Court Order', url: 'https://www.whatsapp.com/records/login', email: '', telefono: ''}], notas: 'Petición de IP requiere fechas exactas. Identificar cuenta con: teléfono, email o ID de usuario. Indicar expresamente si NO SE DEBE NOTIFICAR al usuario.'},
            google: {id: 'google', dominio: 'google.com', nombre: 'Google', categoria: 'plataformas', queInformacion: ['IPs de sesión', 'Datos de suscriptor', 'Fecha de creación'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email oficial.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Global Law Enforcement', email: 'lis-global@google.com', telefono: ''}], notas: 'Incluir rango de fechas, URL/correo exacto y datos completos del requirente.'},
            mercadolibre: {id: 'mercadolibre', dominio: 'mercadolibre.com.ar', nombre: 'MercadoLibre / MercadoPago', categoria: 'plataformas', queInformacion: ['Usuarios asociados al DNI y estado (activo/inactivo)', 'Correos electrónicos asociados', 'Domicilios aportados', 'Teléfonos de contacto', 'Nombre y apellido vinculados', 'Entidades bancarias', 'Datos biométricos (foto de rostro y DNI)', 'IP/logs de conexión de registro y publicación', 'Publicaciones, ofertas, pagos y transferencias', 'Domicilio de envíos y geoposicionamiento de entrega', 'Empresa de entrega y código de rastreo', 'Datos del receptor y teléfono'], requisitosLegales: ['Oficio con firma digital', 'Email institucional'], procedimiento: 'Enviar PDF al correo de notificaciones. MercadoLibre (grupo amarillo) y MercadoPago (grupo celeste).', tiempoRespuesta: 'Rápido (Estándar) / Lento (Especial)', contactos: [{nombre: 'Notificaciones', email: 'notificaciones@mercadolibre.com', telefono: '011-4640-8000 int 8876'}], notas: 'Identificar por: Nickname, Email, Nro Publicación o Tarjeta (6 primeros + 4 últimos). Un mismo DNI puede tener varios usuarios con distintos emails.'},
            apple: {id: 'apple', dominio: 'apple.com', nombre: 'Apple', categoria: 'plataformas', queInformacion: ['Registro de dispositivos', 'iCloud', 'Compras iTunes', 'Conexiones IP'], requisitosLegales: ['Formulario de Apple PDF firmado'], procedimiento: 'Enviar formulario PDF a email. Tienen portal para congelamiento.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Law Enforcement', email: 'lawenforcement@apple.com', telefono: ''}, {nombre: 'Emergencias', email: 'exigent@apple.com', telefono: ''}], notas: 'Apple NOTIFICA al usuario salvo que la orden judicial lo prohíba expresamente.'},
            microsoft: {id: 'microsoft', dominio: 'microsoft.com', nombre: 'Microsoft (Hotmail, Xbox, Skype)', categoria: 'plataformas', queInformacion: ['Suscripción', 'Registro de IPs', 'Contactos'], requisitosLegales: ['Oficio firmado por Juez', 'Planilla Excel de Microsoft'], procedimiento: 'Enviar Oficio PDF + Planilla Excel. Asunto del correo estandarizado.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'LENS Team', email: 'asklcala@microsoft.com', telefono: ''}], notas: 'Asunto debe ser: PAIS - PROVINCIA - IPP/OFICIO.'},
            twitter: {id: 'twitter', dominio: 'x.com', nombre: 'Twitter', categoria: 'plataformas', queInformacion: ['Conservación de datos', 'Información de cuenta'], requisitosLegales: ['Oficio firmado por Juez'], procedimiento: 'Cargar a través del portal web.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal', url: 'https://legalrequests.twitter.com', email: '', telefono: ''}], notas: 'Buscar el User ID numérico oculto en el código fuente del perfil para asegurar el target.'},
            tiktok: {id: 'tiktok', dominio: 'tiktok.com', nombre: 'TikTok', categoria: 'plataformas', queInformacion: ['Usuario', 'Email/Tel', 'IP de creación', 'Logs de login'], requisitosLegales: ['Formulario TikTok firmado y sellado'], procedimiento: 'Completar DOCX de TikTok, pasar a PDF y enviar.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'legal@tiktok.com', telefono: ''}], notas: 'Videos privados requieren orden de búsqueda.'},
            netflix: {id: 'netflix', dominio: 'netflix.com', nombre: 'Netflix', categoria: 'plataformas', queInformacion: ['Email', 'Facturación', 'IPs de streaming', 'Dispositivos'], requisitosLegales: ['Formulario Netflix firmado por Juez con sellos'], procedimiento: 'Completar PDF de Netflix y enviar por correo.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal Process', email: 'legalprocess@netflix.com', telefono: ''}], notas: 'No guarda contenido, solo metadatos de conexión y pago.'},
            spotify: {id: 'spotify', dominio: 'spotify.com', nombre: 'Spotify', categoria: 'plataformas', queInformacion: ['IPs', 'Dispositivos', 'Ubicación no exacta', 'Datos de pago'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Support', email: 'support@spotify.com', telefono: ''}], notas: ''},
            zoom: {id: 'zoom', dominio: 'zoom.us', nombre: 'Zoom', categoria: 'plataformas', queInformacion: ['Datos dispositivo', 'IP', 'Tiempos de reunión'], requisitosLegales: ['Oficio PDF firmado digitalmente'], procedimiento: 'Enviar por correo. Es necesario el Email del titular de cuenta.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Law Enforcement', email: 'lawenforcement@zoom.us', telefono: ''}], notas: ''},
            dropbox: {id: 'dropbox', dominio: 'dropbox.com', nombre: 'Dropbox', categoria: 'plataformas', queInformacion: ['Nombre', 'Email', 'IPs de acceso', 'Dispositivo'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Compliance', email: 'legalcompliance@dropbox.com', telefono: ''}], notas: 'Urgencias agregar "EmergencyRequest" al Asunto.'},
            yahoo: {id: 'yahoo', dominio: 'yahoo.com', nombre: 'Yahoo / Flickr', categoria: 'plataformas', queInformacion: ['IPs de alta', 'Cuentas asociadas', 'Logs de correo/Messenger'], requisitosLegales: ['Oficio firmado'], procedimiento: 'Enviar PDF firmado digitalmente o vía portal Oath.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'ar-legalpoc@yahoo-inc.com', telefono: ''}], notas: 'Permiten congelamiento por 90 días.'},
            sony: {id: 'sony', dominio: 'playstation.com', nombre: 'Sony Playstation', categoria: 'plataformas', queInformacion: ['IPs de acceso', 'Cuentas', 'Transacciones'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'LE Requests', email: 'LE_legalrequests@playstation.sony.com', telefono: ''}, {nombre: 'Emergencias', email: 'Thomas.Nguyen@sony.com', telefono: ''}], notas: 'Tracking ideal a través de compras en la tienda.'},
            airbnb: {id: 'airbnb', dominio: 'airbnb.com', nombre: 'Airbnb', categoria: 'plataformas', queInformacion: ['Datos de usuario', 'Reservas'], requisitosLegales: ['Oficio PDF firmado y sellado (Inglés)'], procedimiento: 'Cargar a través del portal de autoridades o email PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal', url: 'https://es.airbnb.com/lert', email: '', telefono: ''}, {nombre: 'Mail', email: 'leoinfo@airbnb.com', telefono: ''}], notas: 'Airbnb notifica al usuario salvo orden judicial contraria.'},
            badoo: {id: 'badoo', dominio: 'badoo.com', nombre: 'Badoo', categoria: 'plataformas', queInformacion: ['Datos de registro', 'Conexiones'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Llenar formulario en portal web y adjuntar PDF.', tiempoRespuesta: 'Hasta 30 días', contactos: [{nombre: 'Portal', url: 'https://badoo.com/es/team/contacts/', email: '', telefono: ''}], notas: 'Oficio debe contener ID de usuario o Email.'},
            tinder: {id: 'tinder', dominio: 'tinder.com', nombre: 'Match - Tinder', categoria: 'plataformas', queInformacion: ['Datos de registro', 'Conexiones'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'norma.rivera@match.com', telefono: ''}], notas: ''},
            happn: {id: 'happn', dominio: 'happn.com', nombre: 'Happn', categoria: 'plataformas', queInformacion: ['Datos de registro'], requisitosLegales: ['Oficio en francés firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'gaelle.benoist@happn.fr', telefono: ''}], notas: 'El oficio debe estar en francés.'},
            snapchat: {id: 'snapchat', dominio: 'snapchat.com', nombre: 'Snapchat', categoria: 'plataformas', queInformacion: ['Datos de registro'], requisitosLegales: ['Oficio firmado por Juez con sellos'], procedimiento: 'Enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legal', email: 'lawenforcement@snapchat.com', telefono: ''}], notas: 'Portal de urgencias disponible en lawenforcement.snapchat.com/emergency'},

            // === TRANSPORTE ===
            uber: {id: 'uber', dominio: 'uber.com', nombre: 'Uber', categoria: 'transporte', queInformacion: ['Perfil del usuario y datos filiatorios', 'Viajes en rango de fechas (vehículo, origen y destino)', 'Recorrido por geolocalización GPS', 'Método de pago (si tarjeta: número y entidad bancaria)', 'Servicios utilizados y datos cargados en la plataforma', 'IPs de acceso'], requisitosLegales: ['Oficio firmado por Juez con sellos', 'Email institucional'], procedimiento: 'Ingresar al portal LERT con email institucional y cargar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal LERT', url: 'https://www.lert.uber.com', email: '', telefono: ''}, {nombre: 'Email', email: 'LERT@uber.com', telefono: ''}], notas: 'Conservan registros por 90 días si se solicita. Pueden notificar al usuario/conductor.'},
            cabify: {id: 'cabify', dominio: 'cabify.com', nombre: 'Cabify', categoria: 'transporte', queInformacion: ['Datos de usuario', 'Viajes'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Cargar mediante el portal Jotform de Policía.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Info', email: 'info@cabify.com', telefono: ''}, {nombre: 'Portal', url: 'https://cabify.jotform.com', email: '', telefono: ''}], notas: ''},
            didi: {id: 'didi', dominio: 'didiglobal.com', nombre: 'DiDi', categoria: 'transporte', queInformacion: ['Datos del viaje y ruta', 'Audio grabado del viaje (si el usuario lo activó)', 'Datos del vehículo: placa, año, marca, modelo y color', 'Datos de registro del socio (conductor)', 'Datos de registro del usuario (pasajero)', 'Datos de registro del socio flotilla (dueño del vehículo, si aplica)', 'Otros viajes del socio/usuario con fechas y horas'], requisitosLegales: ['Oficio firmado y sellado por el responsable', 'Debe incluir: fecha, dependencia, número de investigación y tipo de delito'], procedimiento: 'Ingresar al portal LERT de DiDi o enviar oficio PDF por email.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Portal LERT', url: 'http://lert.didiglobal.com/', email: '', telefono: ''}, {nombre: 'Email', email: 'lert@didiglobal.com', telefono: ''}], notas: 'Existen celulares de contacto para delitos flagrantes (Chile/Global).'},

            // === FINANCIERO ===
            uala: {id: 'uala', dominio: 'uala.com.ar', nombre: 'Ualá', categoria: 'financiero', queInformacion: ['Usuarios y estado (activo/inactivo)', 'Correos electrónicos asociados', 'Domicilios aportados', 'Teléfonos de contacto', 'Nombre y apellido vinculados', 'Entidades bancarias', 'IP/logs de conexión', 'Pagos, transferencias y movimientos de cuenta'], requisitosLegales: ['Oficio en hoja oficial, formato PDF', 'Firma digital identificable'], procedimiento: 'Enviar oficio PDF por email institucional.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'legales.ar@uala.com.ar', telefono: '011-52633563'}], notas: ''},
            personal_pay: {id: 'personal_pay', dominio: 'personalpay.com.ar', nombre: 'Personal Pay (Microsistemas S.A.U.)', categoria: 'financiero', queInformacion: ['Datos de registración: CUIL, email, fecha', 'Búsqueda por Alias, CVU, CUIL o domicilio informado', 'IP de creación de cuenta e IPs de conexión (compras, pagos)', 'Datos biométricos y foto de DNI', 'Movimientos de la cuenta'], requisitosLegales: ['Nota policial + oficio respaldatorio (delegación de Juez/Fiscal)', 'Firma digital identificable', 'Email institucional'], procedimiento: 'Enviar nota policial junto con oficio respaldatorio por email institucional.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Requerimientos', email: 'requerimientosPersonalPay@teco.com.ar', telefono: ''}], notas: 'Se puede identificar por Alias, CVU o CUIL. Incluye datos biométricos.'},
            paypal: {id: 'paypal', dominio: 'paypal.com', nombre: 'PayPal', categoria: 'financiero', queInformacion: ['Transacciones', 'Cuentas'], requisitosLegales: ['Oficio Judicial'], procedimiento: 'Cargar en portal SafetyHub.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Law Enforcement', email: 'lawenforcement@paypal.com', telefono: ''}], notas: 'Responderán solo a correos oficiales a través de su portal.'},
            bna: {id: 'bna', dominio: 'bna.com.ar', nombre: 'Banco Nación (BNA)', categoria: 'financiero', queInformacion: ['Cuentas', 'Cámaras de seguridad', 'Cajeros'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF. Hay correos específicos por sucursal (ej: 0094pop@bna.com.ar).', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios/Fraudes', email: 'operaciones-atm-analisisdefraudes@bna.com.ar', telefono: ''}, {nombre: 'Seguridad (Cámaras)', email: 'ariverobrizuela@bna.com.ar', telefono: '011-4347-8644'}], notas: 'Para cámaras actuar rápidamente antes de sobrescritura.'},
            provincia: {id: 'provincia', dominio: 'bapro.com.ar', nombre: 'Banco Provincia (BAPRO)', categoria: 'financiero', queInformacion: ['Cuentas', 'Cámaras de seguridad'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'mdjerakian@bpba.com.ar', telefono: ''}, {nombre: 'Cámaras', email: 'cctvrescatefilmaciones@bpba.com.ar', telefono: '011-4309-3907 int 23907'}], notas: ''},
            santander: {id: 'santander', dominio: 'santander.com.ar', nombre: 'Santander', categoria: 'financiero', queInformacion: ['Cuentas', 'Transacciones'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios', email: 'oficiosdeinformes@santanderrio.com.ar', telefono: ''}], notas: ''},
            galicia: {id: 'galicia', dominio: 'galicia.com.ar', nombre: 'Banco Galicia', categoria: 'financiero', queInformacion: ['Cuentas', 'Transacciones'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Oficios', email: 'oficios.judiciales@bancogalicia.com.ar', telefono: ''}], notas: ''},

            // === REGISTROS ===
            nic: {id: 'nic', dominio: 'nic.ar', nombre: 'Nic Argentina', categoria: 'registros', queInformacion: ['Titularidad de dominios .ar', 'Historial de dominios'], requisitosLegales: ['Oficio Judicial'], procedimiento: 'Consultar web o enviar oficio físico/digital.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Mesa de Entradas', url: 'https://www.nic.ar', email: '', telefono: '011-5235-1166'}], notas: 'San Martín 536 Piso 1, CABA.'},
            aubasa: {id: 'aubasa', dominio: 'aubasa.com.ar', nombre: 'AUBASA', categoria: 'registros', queInformacion: ['Paso de peajes', 'Cámaras'], requisitosLegales: ['Oficio firmado digitalmente'], procedimiento: 'Enviar oficio PDF.', tiempoRespuesta: 'Variable', contactos: [{nombre: 'Legales', email: 'legales@aubasa.com.ar', telefono: ''}], notas: ''}
        }
};

